# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy to Azure Web App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Check project structure
        id: check-structure
        run: |
          if [ -f ".deploy-config.json" ]; then
            echo "Project structure config found"
            PROJECT_TYPE=$(cat .deploy-config.json | grep '"type"' | cut -d'"' -f4)
            echo "type=$PROJECT_TYPE" >> $GITHUB_OUTPUT
          else
            echo "type=simple" >> $GITHUB_OUTPUT
          fi

      # Build for simple projects
      - name: npm install, build, and test
        if: steps.check-structure.outputs.type == 'simple'
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present -- --passWithNoTests

      # Build for monorepo projects (Ares pattern)
      - name: Build monorepo backend
        if: steps.check-structure.outputs.type == 'monorepo'
        run: |
          if [ -d "backend" ] && [ -f "backend/package.json" ]; then
            echo "Building backend..."
            cd backend
            npm install
            npm run build --if-present
            npm run test --if-present -- --passWithNoTests
            cd ..
          fi

      - name: Zip artifact for deployment
        run: |
          echo "Creating deployment package..."
          # Include all files but exclude node_modules to keep package small
          zip -r release.zip .             -x "*/node_modules/*"             -x "node_modules/*"             -x ".git/*"             -x "*.log"             -x ".env"             -x "frontend/node_modules/*"             -x "backend/node_modules/*"
          echo "Package created successfully"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'expandev-06'
          package: .